// <auto-generated />
using System;
using GestionTareas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionTareas.Migrations
{
    [DbContext(typeof(GestionProyectosContext))]
    partial class GestionProyectosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionTareas.Models.Archivo", b =>
                {
                    b.Property<int>("ArchivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ArchivoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchivoId"));

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProyectoId")
                        .HasColumnType("int")
                        .HasColumnName("ProyectoID");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TareaId")
                        .HasColumnType("int")
                        .HasColumnName("TareaID");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ArchivoId")
                        .HasName("PK_dbo.Archivo");

                    b.HasIndex(new[] { "ProyectoId" }, "IX_ProyectoID");

                    b.HasIndex(new[] { "TareaId" }, "IX_TareaID");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_UsuarioID");

                    b.ToTable("Archivo", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Comentario", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComentarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComentarioId"));

                    b.Property<string>("ComentarioTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaComentario")
                        .HasColumnType("datetime");

                    b.Property<int>("TareaId")
                        .HasColumnType("int")
                        .HasColumnName("TareaID");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ComentarioId")
                        .HasName("PK_dbo.Comentario");

                    b.HasIndex(new[] { "TareaId" }, "IX_TareaID");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_UsuarioID");

                    b.ToTable("Comentario", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EquipoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EquipoId")
                        .HasName("PK_dbo.Equipo");

                    b.ToTable("Equipo", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.EquipoMiembro", b =>
                {
                    b.Property<int>("EquipoMiembroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EquipoMiembroID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoMiembroId"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int")
                        .HasColumnName("EquipoID");

                    b.Property<string>("RolEnEquipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("EquipoMiembroId")
                        .HasName("PK_dbo.EquipoMiembro");

                    b.HasIndex(new[] { "EquipoId" }, "IX_EquipoID");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_UsuarioID");

                    b.ToTable("EquipoMiembro", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.MigrationHistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContextKey")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte[]>("Model")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("MigrationId", "ContextKey")
                        .HasName("PK_dbo.__MigrationHistory");

                    b.ToTable("__MigrationHistory", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Proyecto", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProyectoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProyectoId")
                        .HasName("PK_dbo.Proyecto");

                    b.ToTable("Proyecto", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.ProyectoEquipo", b =>
                {
                    b.Property<int>("ProyectoEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProyectoEquipoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoEquipoId"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int")
                        .HasColumnName("EquipoID");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int")
                        .HasColumnName("ProyectoID");

                    b.HasKey("ProyectoEquipoId")
                        .HasName("PK_dbo.ProyectoEquipo");

                    b.HasIndex(new[] { "EquipoId" }, "IX_EquipoID");

                    b.HasIndex(new[] { "ProyectoId" }, "IX_ProyectoID");

                    b.ToTable("ProyectoEquipo", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Reporte", b =>
                {
                    b.Property<int>("ReporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReporteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReporteId"));

                    b.Property<string>("Detalles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int")
                        .HasColumnName("ProyectoID");

                    b.Property<string>("TipoReporte")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ReporteId")
                        .HasName("PK_dbo.Reporte");

                    b.HasIndex(new[] { "ProyectoId" }, "IX_ProyectoID");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_UsuarioID");

                    b.ToTable("Reporte", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Reunion", b =>
                {
                    b.Property<int>("ReunionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReunionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReunionId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int")
                        .HasColumnName("ProyectoID");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ReunionId")
                        .HasName("PK_dbo.Reunion");

                    b.HasIndex(new[] { "ProyectoId" }, "IX_ProyectoID");

                    b.ToTable("Reunion", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.ReunionParticipante", b =>
                {
                    b.Property<int>("ReunionParticipanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReunionParticipanteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReunionParticipanteId"));

                    b.Property<int>("ReunionId")
                        .HasColumnType("int")
                        .HasColumnName("ReunionID");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ReunionParticipanteId")
                        .HasName("PK_dbo.ReunionParticipante");

                    b.HasIndex(new[] { "ReunionId" }, "IX_ReunionID");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_UsuarioID");

                    b.ToTable("ReunionParticipante", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId")
                        .HasName("PK_dbo.Rol");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Tarea", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TareaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaId"));

                    b.Property<int?>("AsignadoA")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<string>("Prioridad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int")
                        .HasColumnName("ProyectoID");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId")
                        .HasName("PK_dbo.Tarea");

                    b.HasIndex(new[] { "AsignadoA" }, "IX_AsignadoA");

                    b.HasIndex(new[] { "ProyectoId" }, "IX_ProyectoID");

                    b.ToTable("Tarea", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UsuarioId")
                        .HasName("PK_dbo.Usuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioRolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioRolId"));

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("UsuarioRolId")
                        .HasName("PK_dbo.UsuarioRol");

                    b.HasIndex(new[] { "RolId" }, "IX_RolID");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_UsuarioID");

                    b.ToTable("UsuarioRol", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Archivo", b =>
                {
                    b.HasOne("GestionTareas.Models.Proyecto", "Proyecto")
                        .WithMany("Archivos")
                        .HasForeignKey("ProyectoId")
                        .HasConstraintName("FK_dbo.Archivo_dbo.Proyecto_ProyectoID");

                    b.HasOne("GestionTareas.Models.Tarea", "Tarea")
                        .WithMany("Archivos")
                        .HasForeignKey("TareaId")
                        .HasConstraintName("FK_dbo.Archivo_dbo.Tarea_TareaID");

                    b.HasOne("GestionTareas.Models.Usuario", "Usuario")
                        .WithMany("Archivos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.Archivo_dbo.Usuario_UsuarioID");

                    b.Navigation("Proyecto");

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionTareas.Models.Comentario", b =>
                {
                    b.HasOne("GestionTareas.Models.Tarea", "Tarea")
                        .WithMany("Comentarios")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.Comentario_dbo.Tarea_TareaID");

                    b.HasOne("GestionTareas.Models.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.Comentario_dbo.Usuario_UsuarioID");

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionTareas.Models.EquipoMiembro", b =>
                {
                    b.HasOne("GestionTareas.Models.Equipo", "Equipo")
                        .WithMany("EquipoMiembros")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.EquipoMiembro_dbo.Equipo_EquipoID");

                    b.HasOne("GestionTareas.Models.Usuario", "Usuario")
                        .WithMany("EquipoMiembros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.EquipoMiembro_dbo.Usuario_UsuarioID");

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionTareas.Models.ProyectoEquipo", b =>
                {
                    b.HasOne("GestionTareas.Models.Equipo", "Equipo")
                        .WithMany("ProyectoEquipos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.ProyectoEquipo_dbo.Equipo_EquipoID");

                    b.HasOne("GestionTareas.Models.Proyecto", "Proyecto")
                        .WithMany("ProyectoEquipos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.ProyectoEquipo_dbo.Proyecto_ProyectoID");

                    b.Navigation("Equipo");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GestionTareas.Models.Reporte", b =>
                {
                    b.HasOne("GestionTareas.Models.Proyecto", "Proyecto")
                        .WithMany("Reportes")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.Reporte_dbo.Proyecto_ProyectoID");

                    b.HasOne("GestionTareas.Models.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.Reporte_dbo.Usuario_UsuarioID");

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionTareas.Models.Reunion", b =>
                {
                    b.HasOne("GestionTareas.Models.Proyecto", "Proyecto")
                        .WithMany("Reunions")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.Reunion_dbo.Proyecto_ProyectoID");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GestionTareas.Models.ReunionParticipante", b =>
                {
                    b.HasOne("GestionTareas.Models.Reunion", "Reunion")
                        .WithMany("ReunionParticipantes")
                        .HasForeignKey("ReunionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.ReunionParticipante_dbo.Reunion_ReunionID");

                    b.HasOne("GestionTareas.Models.Usuario", "Usuario")
                        .WithMany("ReunionParticipantes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.ReunionParticipante_dbo.Usuario_UsuarioID");

                    b.Navigation("Reunion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionTareas.Models.Tarea", b =>
                {
                    b.HasOne("GestionTareas.Models.Usuario", "AsignadoANavigation")
                        .WithMany("Tareas")
                        .HasForeignKey("AsignadoA")
                        .HasConstraintName("FK_dbo.Tarea_dbo.Usuario_AsignadoA");

                    b.HasOne("GestionTareas.Models.Proyecto", "Proyecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.Tarea_dbo.Proyecto_ProyectoID");

                    b.Navigation("AsignadoANavigation");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GestionTareas.Models.UsuarioRol", b =>
                {
                    b.HasOne("GestionTareas.Models.Rol", "Rol")
                        .WithMany("UsuarioRols")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.UsuarioRol_dbo.Rol_RolID");

                    b.HasOne("GestionTareas.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRols")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.UsuarioRol_dbo.Usuario_UsuarioID");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionTareas.Models.Equipo", b =>
                {
                    b.Navigation("EquipoMiembros");

                    b.Navigation("ProyectoEquipos");
                });

            modelBuilder.Entity("GestionTareas.Models.Proyecto", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("ProyectoEquipos");

                    b.Navigation("Reportes");

                    b.Navigation("Reunions");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("GestionTareas.Models.Reunion", b =>
                {
                    b.Navigation("ReunionParticipantes");
                });

            modelBuilder.Entity("GestionTareas.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRols");
                });

            modelBuilder.Entity("GestionTareas.Models.Tarea", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("GestionTareas.Models.Usuario", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Comentarios");

                    b.Navigation("EquipoMiembros");

                    b.Navigation("Reportes");

                    b.Navigation("ReunionParticipantes");

                    b.Navigation("Tareas");

                    b.Navigation("UsuarioRols");
                });
#pragma warning restore 612, 618
        }
    }
}
