// <auto-generated />
using System;
using GestionTareas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionTareas.Migrations
{
    [DbContext(typeof(GestionProyectosDbContext))]
    partial class GestionProyectosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionTareas.Models.Archivo", b =>
                {
                    b.Property<int>("ArchivoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchivoID"));

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProyectoID")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TareaID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ArchivoID");

                    b.HasIndex("ProyectoID");

                    b.HasIndex("TareaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Archivos", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Comentario", b =>
                {
                    b.Property<int>("ComentarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComentarioID"));

                    b.Property<DateTime>("FechaComentario")
                        .HasColumnType("datetime2");

                    b.Property<int>("TareaID")
                        .HasColumnType("int");

                    b.Property<string>("TextoComentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Comentario");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ComentarioID");

                    b.HasIndex("TareaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Comentarios", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Equipo", b =>
                {
                    b.Property<int>("EquipoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipoID");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.EquipoMiembro", b =>
                {
                    b.Property<int>("EquipoMiembroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoMiembroID"));

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<string>("RolEnEquipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("EquipoMiembroID");

                    b.HasIndex("EquipoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("EquipoMiembros", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Proyecto", b =>
                {
                    b.Property<int>("ProyectoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProyectoID");

                    b.ToTable("Proyectos", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.ProyectoEquipo", b =>
                {
                    b.Property<int>("ProyectoEquipoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoEquipoID"));

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.HasKey("ProyectoEquipoID");

                    b.HasIndex("EquipoID");

                    b.HasIndex("ProyectoID");

                    b.ToTable("ProyectoEquipos", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Reporte", b =>
                {
                    b.Property<int>("ReporteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReporteID"));

                    b.Property<string>("Detalles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.Property<string>("TipoReporte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ReporteID");

                    b.HasIndex("ProyectoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Reportes", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Reunion", b =>
                {
                    b.Property<int>("ReunionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReunionID"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReunionID");

                    b.HasIndex("ProyectoID");

                    b.ToTable("Reuniones", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.ReunionParticipante", b =>
                {
                    b.Property<int>("ReunionParticipanteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReunionParticipanteID"));

                    b.Property<int>("ReunionID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ReunionParticipanteID");

                    b.HasIndex("ReunionID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("ReunionesParticipantes", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolID");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Tarea", b =>
                {
                    b.Property<int>("TareaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaID"));

                    b.Property<int?>("AsignadoA")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prioridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TareaID");

                    b.HasIndex("AsignadoA");

                    b.HasIndex("ProyectoID");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioRolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioRolID"));

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("UsuarioRolID");

                    b.HasIndex("RolID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("GestionTareas.Models.Archivo", b =>
                {
                    b.HasOne("GestionTareas.Models.Proyecto", "Proyecto")
                        .WithMany("Archivos")
                        .HasForeignKey("ProyectoID");

                    b.HasOne("GestionTareas.Models.Tarea", "Tarea")
                        .WithMany("Archivos")
                        .HasForeignKey("TareaID");

                    b.HasOne("GestionTareas.Models.Usuario", "Usuario")
                        .WithMany("Archivos")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionTareas.Models.Comentario", b =>
                {
                    b.HasOne("GestionTareas.Models.Tarea", "Tarea")
                        .WithMany("Comentarios")
                        .HasForeignKey("TareaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionTareas.Models.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionTareas.Models.EquipoMiembro", b =>
                {
                    b.HasOne("GestionTareas.Models.Equipo", "Equipo")
                        .WithMany("EquipoMiembros")
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionTareas.Models.Usuario", "Usuario")
                        .WithMany("EquipoMiembros")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionTareas.Models.ProyectoEquipo", b =>
                {
                    b.HasOne("GestionTareas.Models.Equipo", "Equipo")
                        .WithMany("ProyectoEquipos")
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionTareas.Models.Proyecto", "Proyecto")
                        .WithMany("ProyectoEquipos")
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GestionTareas.Models.Reporte", b =>
                {
                    b.HasOne("GestionTareas.Models.Proyecto", "Proyecto")
                        .WithMany("Reportes")
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionTareas.Models.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionTareas.Models.Reunion", b =>
                {
                    b.HasOne("GestionTareas.Models.Proyecto", "Proyecto")
                        .WithMany("Reunions")
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GestionTareas.Models.ReunionParticipante", b =>
                {
                    b.HasOne("GestionTareas.Models.Reunion", "Reunion")
                        .WithMany("ReunionParticipantes")
                        .HasForeignKey("ReunionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionTareas.Models.Usuario", "Usuario")
                        .WithMany("ReunionParticipantes")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reunion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionTareas.Models.Tarea", b =>
                {
                    b.HasOne("GestionTareas.Models.Usuario", "UsuarioAsignado")
                        .WithMany("Tareas")
                        .HasForeignKey("AsignadoA");

                    b.HasOne("GestionTareas.Models.Proyecto", "Proyecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("UsuarioAsignado");
                });

            modelBuilder.Entity("GestionTareas.Models.UsuarioRol", b =>
                {
                    b.HasOne("GestionTareas.Models.Rol", "Rol")
                        .WithMany("UsuarioRols")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionTareas.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRols")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionTareas.Models.Equipo", b =>
                {
                    b.Navigation("EquipoMiembros");

                    b.Navigation("ProyectoEquipos");
                });

            modelBuilder.Entity("GestionTareas.Models.Proyecto", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("ProyectoEquipos");

                    b.Navigation("Reportes");

                    b.Navigation("Reunions");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("GestionTareas.Models.Reunion", b =>
                {
                    b.Navigation("ReunionParticipantes");
                });

            modelBuilder.Entity("GestionTareas.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRols");
                });

            modelBuilder.Entity("GestionTareas.Models.Tarea", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("GestionTareas.Models.Usuario", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Comentarios");

                    b.Navigation("EquipoMiembros");

                    b.Navigation("Reportes");

                    b.Navigation("ReunionParticipantes");

                    b.Navigation("Tareas");

                    b.Navigation("UsuarioRols");
                });
#pragma warning restore 612, 618
        }
    }
}
